version: "3.9"

services:
  flowback-postgresql:
    image: postgres:16.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: flowback
      POSTGRES_PASSWORD: flowback
      POSTGRES_DB: flowback
#    volumes:
#      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  flowback-redis:
    image: redis:5
    restart: unless-stopped
    ports:
      - 6379:6379

  flowback-rabbitmq:
    image: rabbitmq:3.13
    hostname: flowback
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=flowback
      - RABBITMQ_DEFAULT_PASS=flowback
      - RABBITMQ_DEFAULT_VHOST=flowback
    ports:
      - 5672:5672
      - 15672:15672